added converstion to wmc

diff --git a/main b/main
--- a/main
+++ b/main
@@ -127,11 +127,12 @@ done
 
 
 echo "Running LAP multi example"
+mkdir tracts_tck;
 while read tract_name; do
 	echo "Tract name: $tract_name"; 
 	base_name=$tract_name'_tract'
 	run=`jq -r '.run' config.json`
-	output_filename=${subjID}'_'$base_name'_'$run'.tck'
+	output_filename=tracts_tck/${subjID}'_'$base_name'_'$run'.tck'
 	array_filename='result_lap'
 	python lap_multiple_examples.py -moving_dir tractograms_directory -static $subjID'_track.trk' -ex_dir examples_directory_$tract_name -out $output_filename;
 	#singularity exec docker://brainlife/dipy:0.14 python ./lap_multiple_examples.py -moving_dir tractograms_directory -static ${subjID}_track.trk -ex_dir examples_directory -out $output_filename
@@ -145,5 +146,28 @@ while read tract_name; do
 	fi
 done < tract_name_list.txt
 
+
+echo "Build partial tractogram"
+output_filename=${subjID}'_var-partial_tract_E'${run}'.tck';
+python build_partial_tractogram.py -tracts_tck_dir 'tracts_tck' -out ${output_filename};
+#singularity exec -e docker://brainlife/dipy:0.14 python ./build_partial_tractogram.py -tracts_tck_dir tracts_tck -out $output_filename
+if [ -f ${output_filename} ]; then 
+    echo "Partial tractogram built."
+else 
+	echo "Partial tractogram missing."
+	exit 1
+fi
+
+echo "Build a wmc structure"
+stat_sub=\'$subjID\'
+mov_sub=\'$mov_afq_id\'
+matlab -nosplash -nodisplay -r "build_wmc_structure($stat_sub, $run)";
+#singularity exec docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/build_wmc_structure $subjID $mov_afq_id
+if [ -f 'output.mat' ]; then 
+    echo "WMC structure created."
+else 
+	echo "WMC structure missing."
+	exit 1
+fi
 
 echo "Complete"
